# Generated by Django 5.2.8 on 2025-11-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('medical_record_number', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('medical_history', models.TextField()),
            ],
        ),
    ]
