# Generated by Django 5.2.8 on 2025-11-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0002_medicalrecords_patient_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicalRecords',
            new_name='MedicalRecord',
        ),
    ]
